version: 2.1
executors:
  npm:
    working_directory: ~/ngv-form-decorators
    docker:
      - image: circleci/node:10-browsers-legacy
jobs:
  build:
    executor: npm
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: restore_cache-{{ checksum "package.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint ngv-form-decorators
      - run:
          name: test
          command: npm run test ngv-form-decorators -- --watch false --code-coverage   --progress false
      - store_test_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: coverage
          command:  bash <(curl -s https://codecov.io/bash)
      - run:
          name: build
          command: npm run build ngv-form-decorators
workflows:
  version: 2.1
  build:
    jobs:
      - build
