version: 2.1
executors:
  npm:
    working_directory: ~/ngv-form-decorators
    docker:
      -image: circleci/node:10.15.2
jobs:
  build:
    executor: npm
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: restore_cache-{{ checksum "package.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint ngv-form-decorators
