version: 2.1
executors:
  npm:
    working_directory: ~/ngv-form-decorators
    docker:
      - image: circleci/node:10-browsers-legacy
jobs:
  update_dependencies:
    executor: npm
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: restore_cache-{{ checksum "package.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    executor: npm
    branches:
      ignore:
        - gh-pages
    steps:
      - run:
          name: lint
          command: npm run lint ngv-form-decorators
      - run:
          name: build
          command: npm run build ngv-form-decorators
      - store_artifacts:
          path: dist/ngv-form-decorators
          destination: ngv-form-decorators
  test:
    executor: npm
    branches:
      ignore:
        - gh-pages
    steps:
      - run:
          name: test
          command: npm run test ngv-form-decorators -- --watch false --code-coverage   --progress false
      - store_test_results:
          path: coverage/icov.info
          destination: coverage/icov.info
      - run:
          name: coverage
          command:  bash <(curl -s https://codecov.io/bash)
  build-docs:
    executor: npm
    branches:
      ignore:
        - gh-pages
    steps:
      - run:
          name: docs-build
          command: npm run build -- --prod --base-href "https://ng-veteran.github.io/ngv-form-decorators/"
      - store_artifacts:
          path: dist/ngv-form-decorators-demo
          destination: ngv-form-decorators-demo
  deploy-docs:
    executor: npm
    branches:
      ignore:
        - gh-pages
    steps:
      - run:
          name: docs-deploy
          command: npx angular-cli-ghpages --dir dist/ngv-form-decorators-demo
workflows:
  version: 2.1
  update_build_test_deploy-docs:
    jobs:
      - update_dependencies
      - test:
          requires:
            - update_dependencies
      - build:
          requires:
            - update_dependencies
      - build-docs:
          requires:
            - update_dependencies
      - deploy-docs:
          requires:
            - build-docs

